namespace: argocd
releases:
- chart: argo/argo-cd
  name: argocd
  version: 4.10.5
  values:
  - ../../versionStream/charts/argocd/argocd/values.yaml.gotmpl
  - values.yaml
- chart: ../../charts/argo-applications
  name: argo-applications
