# Source: argo-cd/templates/argocd-repo-server/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: argo-cd-4.10.5
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: argocd-repo-server
  annotations:
    meta.helm.sh/release-name: 'argocd'
  namespace: argocd
spec:
  ports:
    - name: https-repo-server
      protocol: TCP
      port: 8081
      targetPort: repo-server
  selector:
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/instance: argocd
